### ISSUE TITLE
[Bug]: Too new Java used for building, results in errors on PyCharm 2022.1.2

### ISSUE THREAD

**Issue by samip5** [Testaustime/testaustime-intellij#2]
It seems that too new Java has been used to compile the classes, as I'm getting this on PyCharm 2022.1.2.

```
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

```
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create listener fi.testaustime.plugin_intellij.listeners.TestaustimeServiceListener [Plugin: fi.testaustime.plugin_intellij]
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:920)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:177)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:147)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:349)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:141)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.lambda$publish$0(CompositeMessageBus.java:103)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:103)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:176)
	at com.sun.proxy.$Proxy38.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:98)
	at com.intellij.idea.IdeStarter.main(IdeStarter.kt:79)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:176)
	at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class fi.testaustime.plugin_intellij.listeners.TestaustimeServiceListener (
  error: fi/testaustime/plugin_intellij/listeners/TestaustimeServiceListener has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Testaustime, id=fi.testaustime.plugin_intellij, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.5787.24.plugins/testaustime-intellij, version=0.2.0, package=null, isBundled=false), packagePrefix=null, instanceId=23, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:412)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:240)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1469)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:917)
	... 22 more
Caused by: java.lang.UnsupportedClassVersionError: fi/testaustime/plugin_intellij/listeners/TestaustimeServiceListener has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:263)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:111)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:179)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:404)
	... 26 more
```

**Comment by bluelhf** [comment]
This issue is caused by PyCharm utilising an older LTS release of Java, namely 11. For now, we can compile with Java 11 to support PyCharm, but the IDE also ought to follow IDEA's lead in updating to Java 17.

Should be fixed just by changing the Java version in the properties from 17 to 11.

**Comment by samip5** [comment]
> This issue is caused by PyCharm utilising an older LTS release of Java, namely 11. For now, we can compile with Java 11 to support PyCharm, but the IDE also ought to follow IDEA's lead in updating to Java 17.
> 
> Should be fixed just by changing the Java version in the properties from 17 to 11.

Same can be said for IntelliJ IDEA Ultimate version 2022.1.2 as that also uses Java 11.

**Comment by bluelhf** [comment]
> > This issue is caused by PyCharm utilising an older LTS release of Java, namely 11. For now, we can compile with Java 11 to support PyCharm, but the IDE also ought to follow IDEA's lead in updating to Java 17.
> > Should be fixed just by changing the Java version in the properties from 17 to 11.
> 
> Same can be said for IntelliJ IDEA Ultimate version 2022.1.2 as that also uses Java 11.

Yes; IDEA 2022.2 supports Java 17:
> As of v2022.2, all IntelliJ IDEA updates come with JetBrains Runtime 17 (JBR 17), which brings a significant IDE performance improvement, better security, enhanced rendering performance on macOS thanks to the [Metal API](https://developer.apple.com/metal/), and more.

For end-users facing this issue, it is possible to temporarily [instruct JetBrains IDEs to run on JBR 17 instead](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under?page=5), which should fix the issue. JBR 17 binaries can, in turn, be downloaded [here](https://github.com/JetBrains/JetBrainsRuntime/releases).

**Comment by samip5** [comment]
Ah, my toolbox hadn't said there's an update. User error. :)
